apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp-gke.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "webapp-gke.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
